<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Compartilhado\" />
    <Folder Include="Modulos\ModuloEstoque\Base\" />
    <Folder Include="Modulos\ModuloEstoque\Base\Apresentacao\" />
    <Folder Include="Modulos\ModuloEstoque\Base\Dominio\" />
    <Folder Include="Modulos\ModuloEstoque\Base\Infra\" />
    <Folder Include="Modulos\ModuloEstoque\RequisicaoDeEntrada\" />
    <Folder Include="Modulos\ModuloEstoque\RequisicaoDeEntrada\Apresentacao\" />
    <Folder Include="Modulos\ModuloEstoque\RequisicaoDeEntrada\Dominio\" />
    <Folder Include="Modulos\ModuloEstoque\RequisicaoDeEntrada\Infra\" />
    <Folder Include="Modulos\ModuloFuncionarios\Infra\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
  </ItemGroup>
</Project>