<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Compartilhado\" />
    <Folder Include="ModuloMedicamentos\" />
    <Folder Include="ModuloFornecedores\Dominio\" />
    <Folder Include="ModuloFornecedores\infra\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
